<?php
	session_start();
	include($_SERVER['DOCUMENT_ROOT'].'/dictionary/resources/connections/update.php');

	$login = mysqli_real_escape_string($conn,$_POST['email']);

	$randomPassword = bin2hex(random_bytes(5));

	$query = "UPDATE users u SET u.Password = '".password_hash($randomPassword,PASSWORD_DEFAULT)."' WHERE u.Login = '".$login."'";
	$result = mysqli_query($conn,$query);
	if($result){
		//$msg = "Hello! \n A request for new password was made.\n Your new password: ".$randomPassword."\n Remember to change it!\n Message was generated by script. Please don't respond to it.";
		//mail($login,'IT Dictionary user password reset',$msg);		
		$_SESSION['error']=$randomPassword;
		$path="location:../"
	}
	else{
		$path="location:./"
		$_SESSION['error']="Request failed. Check for typos and try again.";
	}
	mysqli_close($conn);

	header($path);	
?>